[package]
name = "image-2-ascii-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
image = "0.25.1"
imageproc = "0.24.0"
ratatui = "0.26.2"
term_size = "0.3.2"

